[package]
name = "tree_viewer"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
postgresql-cst-parser = { git = "https://github.com/future-architect/postgresql-cst-parser", branch = "fix/fix-range-bug"}
